In [3]:
import numpy as np

In [4]:
#init a np array
a=np.array([1,2,3])
a

array([1, 2, 3])

In [5]:
b=np.array([[0.9,8.0,1.1],[0.1,0.2,0.3]])
b

array([[0.9, 8. , 1.1],
       [0.1, 0.2, 0.3]])

In [6]:
#Get Dimenstion
b.ndim

2

In [7]:
#Get Shape
b.shape

(2, 3)

In [8]:
#Get data type
print(a.dtype)
print(b.dtype)

int32
float64


In [9]:
#Get Size , size for each element in bytes
b.itemsize

8

In [10]:
#Get total size
print(b.itemsize*b.size)
print(b.nbytes)

48
48


In [11]:
#Access specific row, colum, element

In [12]:
ar=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
ar

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [13]:
#Get a specific element by arr [r,c]
ar[1,5]

13

In [14]:
#Get a specific row
ar[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [15]:
ar[:,5]

array([ 6, 13])

In [16]:
ar[1,5]=111
ar

array([[  1,   2,   3,   4,   5,   6,   7],
       [  8,   9,  10,  11,  12, 111,  14]])

In [17]:
ar[1,:]=[5,5,5,5,5,5,5]
ar

array([[1, 2, 3, 4, 5, 6, 7],
       [5, 5, 5, 5, 5, 5, 5]])

In [18]:
#init arrays

In [19]:
#All 0's array
a=np.zeros([5,5])
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [20]:
#All 1's matrix
a=np.ones((5,5))
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [21]:
##init with arbitary number
a=np.full([5,5],1001)
a

array([[1001, 1001, 1001, 1001, 1001],
       [1001, 1001, 1001, 1001, 1001],
       [1001, 1001, 1001, 1001, 1001],
       [1001, 1001, 1001, 1001, 1001],
       [1001, 1001, 1001, 1001, 1001]])

In [22]:
#Any other number (full_like)
a=np.full_like(ar,101)
a

array([[101, 101, 101, 101, 101, 101, 101],
       [101, 101, 101, 101, 101, 101, 101]])

In [23]:
np.random.rand(4,2)

array([[0.11209341, 0.33828525],
       [0.52674538, 0.19052705],
       [0.31594148, 0.55426821],
       [0.24460513, 0.33463265]])

In [24]:
#Random Ineger values
np.random.randint(-100,100,size=ar.shape)

array([[ 44,  36,  98,  61,  37, -57,  99],
       [ 69,  24,  -3,  51,  83, -74, -65]])

In [25]:
#Identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [26]:
arr=np.array([[1,2,3]])
a=np.repeat(arr,3,axis=0)
a

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [27]:
op=np.ones([5,5])
ze=np.zeros([3,3])
ze[1,1]=9
op[1:4,1:4]=ze
op

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

Copy array

In [28]:
A=np.array([1,2,3])
B=A.copy();
B[1]=111
print(B)
print(A)

[  1 111   3]
[1 2 3]


Math ops

In [29]:
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [30]:
a+2

array([3, 4, 5, 6, 7])

In [31]:
a*3

array([ 3,  6,  9, 12, 15])

In [32]:
a/2

array([0.5, 1. , 1.5, 2. , 2.5])

In [33]:
b=np.array([5,4,3,2,1])
a+b

array([6, 6, 6, 6, 6])

In [36]:
a**2

array([ 1,  4,  9, 16, 25], dtype=int32)

In [39]:
np.sin(a)
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219])

Linear Algebra

In [43]:
a=np.full((2,3),1)
print(a)
b=np.full((3,2),2)
print(b)

np.matmul(a,b)

[[1 1 1]
 [1 1 1]]
[[2 2]
 [2 2]
 [2 2]]


array([[6, 6],
       [6, 6]])

In [45]:
c = np.identity(3)
np.linalg.det(c)

1.0

Statistics

In [47]:
stats=np.array([[1,2,3,4],[4,5,6,7]])
stats

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [48]:
np.min(stats)

1

In [52]:
np.max(stats)

7

In [53]:
np.sum(stats)

32

Reorg Array

In [54]:
befor=np.array([[1,2,3,4],[5,6,7,8]])
befor

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [58]:
after=befor.reshape((1,8))
after

array([[1, 2, 3, 4, 5, 6, 7, 8]])

In [59]:
#vertically stacking vectors

In [61]:
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])

np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [63]:
h1=np.ones((2,3))
h2=np.zeros((2,3))

np.hstack((h1,h2))

array([[1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.]])

Extra

In [67]:
filedata=np.genfromtxt("data.txt",delimiter=",")
filedata=filedata.astype('int')
filedata

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]])

Advanced Indexing

In [68]:
filedata >50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [72]:
np.all(filedata>50,axis=0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [73]:
np.any(filedata>50,axis=0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])